name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with SSH
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd KSTU_Unoficial_API
            make update
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER_NAME }}
          key: ${{ secrets.PRIVATE_KEY }}
